---
kind: pipeline
name: mirror-to-github

steps:
  - name: validate-openapi
    image: openapitools/openapi-generator-cli
    commands:
      - echo "calling openapi-generator-cli to validate spec/openapi.yaml"
      - docker-entrypoint.sh validate -i spec/openapi.yaml --recommend

  - name: pull-connect-api-server
    image: registry.dev.wisetime.com/alpine-git-bash
    environment:
      JOB_SSH_KEY_B64:
        from_secret: git-ssh-key-b64
    commands:
      - git clone https://stash.practiceinsight.io/stash/scm/wtcom/connect-api-server.git
      - mkdir -p ~/.ssh && ssh-keyscan -p 7999 -t rsa stash.practiceinsight.io >> ~/.ssh/known_hosts
      - echo "$${JOB_SSH_KEY_B64}" | base64 -d > ~/.ssh/job.key && chmod 600 ~/.ssh/job.key
      - cd connect-api-server
      - GIT_SSH_COMMAND='ssh -i ~/.ssh/job.key' git submodule update --init

  - name: test-connect-api-server
    image: azul/zulu-openjdk:11
    environment:
      GRADLE_USER_HOME: .gcache
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
      POSTGRES_TEST_HOST: postgres-service
      REDIS_TEST_HOST: redis-service
    commands:
      - cd connect-api-server
      - echo $${DRONE_MACHINE}
      - ./gradlew -Pgenurl='/drone/src/spec/openapi.yaml' test

  - name: github-push
    image: quay.io/wt-build-support/alpine-git-bash
    environment:
      GITHUB_SSH_KEY_B64:
        from_secret: github-ssh-key-b64
    commands:
      - bin/mirror.sh
    when:
      ref:
        - refs/heads/master
        - refs/tags/*

trigger:
  event:
    - push
    - tag

services:
  - name: postgres-service
    image: registry.dev.wisetime.com/test/postgres:latest
    pull: always

  - name: redis-service
    image: redis:4.0.14-alpine

---
kind: secret
name: git-ssh-key-b64
get:
  path: drone/stash/submodule-rsa
  name: submod-key-b64

---
kind: secret
name: github-ssh-key-b64
get:
  path: drone/publish/github/connect-api-spec
  name: gh-connect-api-spec-key-b64
