---
kind: pipeline
name: mirror-to-github

steps:
  - name: validate-openapi
    image: openapitools/openapi-generator-cli
    commands:
      - echo "calling openapi-generator-cli to validate spec/openapi.yaml"
      - docker-entrypoint.sh validate -i spec/openapi.yaml --recommend
  - name: github-push
    image: quay.io/wt-build-support/alpine-git-bash
    environment:
      GITHUB_SSH_KEY_B64:
        from_secret: github-ssh-key-b64
    commands:
      - bin/mirror.sh
    when:
      ref:
        - refs/heads/master
        - refs/tags/*

trigger:
  event:
    - push
    - tag

---
kind: secret
name: github-ssh-key-b64
get:
  path: drone/publish/github/connect-api-spec
  name: gh-connect-api-spec-key-b64
