---
kind: pipeline
name: mirror-to-github
depends_on:
  - test-and-publish

steps:
  - name: validate
    image: openapitools/openapi-generator-cli
    commands:
      - echo $${DRONE_MACHINE}
      - java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar validate -i ./spec/openapi.yaml
  - name: github-push
    image: quay.io/wt-build-support/alpine-git-bash
    environment:
      GITHUB_SSH_KEY_B64:
        from_secret: github-ssh-key-b64
    commands:
      - ./mirror.sh
    when:
      ref:
        - refs/heads/master
        - refs/tags/*

trigger:
  event:
    - push
    - tag

---
kind: secret
name: github-ssh-key-b64
get:
  path: drone/publish/github/inpro-jira
  name: gh-jira-key-b64
